#!/bin/bash
#------------------------------------------------------------------------------
#
# Package : thinkpad-dock
#
# Provides : preinstallation routines
#
#------------------------------------------------------------------------------
# --- Start Pre Install Script
#------------------------------------------------------------------------------

upgrade()
{
   #--------------------------------------
   # Stop the service while we are upgrading
   if systemctl status thinkpad-dock | grep -q 'Active: active (running)'
   then
      systemctl stop thinkpad-dock
   fi
}

   case $1 in
      upgrade)
         upgrade
         ;;
      *) ;;
   esac

   exit 0

#------------------------------------------------------------------------------
# --- End Pre Install Script
#------------------------------------------------------------------------------
