#!/bin/bash
#------------------------------------------------------------------------------
#
# Package: thinkpad-dock
#
# Provides: prerm - pre-removal script
#
#------------------------------------------------------------------------------
#--- Main Code
#------------------------------------------------------------------------------

remove_package()
{
   scripts="$( ls /etc/thinkpad-dock/scripts/ )"

   if [[ -z ${scripts} ]]
   then
      rm -rf /etc/thinkpad-dock/scripts/
   else
      echo "INFO: /etc/thinkpad-dock/scripts/ is not empty, not removing"
   fi

   if systemctl disable thinkpad-dock.service
   then
      rm -f /etc/systemd/system/thinkpad-dock.service
   else
      echo "ERR: unable to remove thinkpad-dock.service"
      return 1
   fi
}

case $1 in
   remove|purge)
      remove_package || exit $?
      ;;
   *) exit 0
      ;;
esac

#------------------------------------------------------------------------------
#--- End Script
#------------------------------------------------------------------------------
